// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjbaZ9XmJNyT28zPqcEjYnDQXh93Uiy6w',
    appId: '1:344813659013:web:dbb4c1213a4499863d1aec',
    messagingSenderId: '344813659013',
    projectId: 'catatan-harian-2139e',
    authDomain: 'catatan-harian-2139e.firebaseapp.com',
    storageBucket: 'catatan-harian-2139e.appspot.com',
    measurementId: 'G-7KLKDGK14X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcUaJEazrUsVWJ4FGO3zmsxQRiRuPCgfo',
    appId: '1:344813659013:android:62ee01f817fdcaf83d1aec',
    messagingSenderId: '344813659013',
    projectId: 'catatan-harian-2139e',
    storageBucket: 'catatan-harian-2139e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0bUdS1Qu6Zu2p8RAuJxcuXF7H6KPjfJ0',
    appId: '1:344813659013:ios:23b7af24b0a254983d1aec',
    messagingSenderId: '344813659013',
    projectId: 'catatan-harian-2139e',
    storageBucket: 'catatan-harian-2139e.appspot.com',
    iosClientId: '344813659013-b81l2sprbper72r38887ho6l053n9eoe.apps.googleusercontent.com',
    iosBundleId: 'dev.triyono.catatanHarian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0bUdS1Qu6Zu2p8RAuJxcuXF7H6KPjfJ0',
    appId: '1:344813659013:ios:23b7af24b0a254983d1aec',
    messagingSenderId: '344813659013',
    projectId: 'catatan-harian-2139e',
    storageBucket: 'catatan-harian-2139e.appspot.com',
    iosClientId: '344813659013-b81l2sprbper72r38887ho6l053n9eoe.apps.googleusercontent.com',
    iosBundleId: 'dev.triyono.catatanHarian',
  );
}
